language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: R4e4nmMzWCJ+Und60kJGjwALPSOSCx+Zmzzc193D7RhafHwdSB1569lcaudTWVR3eOjbbV1Ff5Jy+iFrepD3xyZ0StvDKJuVouWTBh19T3QphY/kzj0fxpZGbWPH1FBsdQk4AmcTTJ3kJtKBA2PPr99ZfsoZxF0HLf4xoJzYqJtnqdF5OAdLPq81cUlReA9CB/b78yAcNin1dFGuiQB9WQux/TieZ0m4yBcKFVHwanwNe1E1tXL6qn4k1hHvH1D289QOgBvSiM3aQ6nWDcGM2JWLzecJJNOfsTILDLFYyVhmEqeyIYPj0EbJU7KaD8c5v04yLYBif8/WtK9X8+5i4xOV8MlFoVdZqSOlJimB2pOH2BKadNti4wrtUlpxTUwchy6DpTv9MCMcL4z+eEJe4DIeK8LPC4imkyotlwohsAclt7duo9n7r1oGK4K2j4V3c35MBJtkEeeYfkVBLMPuOOv9+DI880pitWpu8Aqb1PN45NDEuhDIJ7rWeS28uv8WApFlW0ey75KRcxyukNtUxPXQcZO4gJkIpObSjkAPK+rVdzjs44ucVApzfkCXGFXwbjSjqv7A19lAfk/tW+2m9C9OCr40af2SS9M84AMHcKF3Ce+LVD1a5NiTcxdzqCDeo8pYx/jqL5qutVAU0wIBHCiCnfp43t5thoBlewnm26U=
  app: course-blocks
  on:
    repo: jeffbernst/node-capstone
env:
  matrix:
    secure: A2F5GXWh1XhHcxZ7nSgRmlvjMU8qJpRkgzBLKBppO50ILyeunjvjxmC8Asb95wFyQ5F1fWJcjE0s/68Kb6TYk2DtxJbQLzIrkiapiWSDx/uea+yt+7xGNaJyZZn6c0qu7E4JRf+nXiOIUkFijWwSu4fmV4gXNxwWOfKYI3BoLr/acDLhapUtcgc2pNvNv4vITRJTUEbimExpi3uv5/D0zupEOahljMg2GJFIdg1h7M6dnPmWsM7nquasLTQQ+YW1ixLZ+33v7kGdRaCY1E4jK7s/VELUMnHwi1FON2z0yJ2T0u2tyiXtXtLKBFRg1of5iEcrEA/v+7sdWSZ6vjj/zusjcGq1TD8SvoOJTGi0e50y3umpFfNXIUdzwoNO21cwKtdCGIGySJ0HJ/PzgNHiIcCODbhYqJXuH4Xie2zYQnMEIsKn0x7LVcc+J3kFczYWEpAMotCXiowm+/LlLYI/oBEgzW6AEHMDQvdQoGTpOTMC2p7hnjyUejGF8iTPtBZENmMi13WafANOKK3/xjxarui0C/lhNd/kzqpvQ2HWGh7/eAAYgUMYg9EZbQD4zsBW1r5LqgmRlFAfk/xyxwD6qyDmf8mOL0cZuqF6sHfuvF/BWDpz9BuEJM1dZ3TzqqVz1WJZFwqNjOtD7NbiMpkxLw2KR7U1wEW1lIQOqR9gI98=
